// ========================================
// カードデータ & ロジック
// ========================================

export const CARD_TEMPLATES = [
  // === 営業系 ===
  {
    id: 'sales_cold',
    name: '飛び込み営業',
    category: 'sales',
    categoryLabel: '営業',
    icon: '🚶',
    description: '片っ端から電話してアポを取る。泥臭いが基本。',
    cost: 0,
    revenueMin: 50000,
    revenueMax: 200000,
    failRate: 0.40,
    failText: '全滅。アポすら取れなかった。',
    successText: '1件獲得！',
    rarity: 1,
    count: 4,
    period: 1,
  },
  {
    id: 'sales_network',
    name: '交流会に参加',
    category: 'sales',
    categoryLabel: '営業',
    icon: '🤝',
    description: '異業種交流会で名刺を配りまくる。',
    cost: 30000,
    revenueMin: 100000,
    revenueMax: 300000,
    failRate: 0.30,
    failText: '名刺交換だけで終わった。',
    successText: '交流会で見込み客を見つけた！',
    rarity: 1,
    count: 3,
    period: 1,
  },
  {
    id: 'sales_sns',
    name: 'SNSで発信',
    category: 'sales',
    categoryLabel: '営業',
    icon: '📱',
    description: '実績や知見を投稿。じわじわ効いてくる。',
    cost: 0,
    revenueMin: 0,
    revenueMax: 150000,
    failRate: 0.55,
    failText: 'いいね3件。反応なし。',
    successText: '投稿がバズった！問い合わせが来た！',
    rarity: 1,
    count: 3,
    cumulative: true,
    cumulativeBonus: 20000,
    cumulativeBonusLabel: 'SNS蓄積効果',
    period: 1,
  },
  {
    id: 'sales_referral',
    name: '紹介営業',
    category: 'sales',
    categoryLabel: '営業',
    icon: '💬',
    description: '既存客や知人からの紹介。信用がないと来ない。',
    cost: 0,
    revenueMin: 200000,
    revenueMax: 500000,
    failRate: 0.20,
    failText: '紹介先と条件が合わなかった。',
    successText: '紹介案件を受注！信頼のおかげだ。',
    rarity: 2,
    count: 2,
    period: 2,
    requirement: { creditScore: 30 },
    requirementText: '信用スコア30以上で解放',
  },
  {
    id: 'sales_enterprise',
    name: '大手に提案',
    category: 'sales',
    categoryLabel: '営業',
    icon: '🏢',
    description: '大手企業にDM。当たればデカい。',
    cost: 50000,
    revenueMin: 500000,
    revenueMax: 2000000,
    failRate: 0.60,
    failText: '提案書すら見てもらえなかった。',
    successText: '大手案件を受注！！デカい！！',
    rarity: 3,
    count: 1,
    period: 2,
  },
  {
    id: 'sales_repeat',
    name: 'リピーター対応',
    category: 'sales',
    categoryLabel: '営業',
    icon: '🔄',
    description: '既存客に追加提案。安定の売上。',
    cost: 0,
    revenueMin: 150000,
    revenueMax: 350000,
    failRate: 0.10,
    failText: '今は追加の予算がないそうだ。',
    successText: 'リピーターから追加受注！',
    rarity: 2,
    count: 2,
    period: 2,
    requirement: { totalRevenue: 5000000 },
    requirementText: '累計売上Ƴ500万以上で解放',
  },

  // === 投資系 ===
  {
    id: 'invest_ad',
    name: 'SNS広告',
    category: 'invest',
    categoryLabel: '投資',
    icon: '📢',
    description: '広告を打って集客する。即効性あり。',
    cost: 150000,
    revenueMin: 200000,
    revenueMax: 600000,
    failRate: 0.20,
    failText: '広告費だけ消えた…。ターゲット設定が甘かった。',
    successText: '広告経由で問い合わせが増えた！',
    rarity: 1,
    count: 2,
    period: 1,
  },
  {
    id: 'invest_website',
    name: 'Webサイト作成',
    category: 'invest',
    categoryLabel: '投資',
    icon: '🌐',
    description: '会社のWebサイトを作る。信用と集客の基盤。',
    cost: 300000,
    permanent: true,
    permanentEffect: { revenueBase: 50000, creditScore: 5 },
    permanentLabel: '毎月の売上ベース+Ƴ5万 / 信用+5',
    failRate: 0,
    rarity: 2,
    count: 1,
    period: 1,
    unique: true,
  },
  {
    id: 'invest_office',
    name: 'オフィスを借りる',
    category: 'invest',
    categoryLabel: '投資',
    icon: '🏠',
    description: '自宅から脱出。信用UPだが固定費が重い。',
    cost: 500000,
    permanent: true,
    permanentEffect: { creditScore: 10, monthlyExpense: 150000 },
    permanentLabel: '信用+10 / 毎月固定費+Ƴ15万',
    failRate: 0,
    rarity: 2,
    count: 1,
    period: 1,
    unique: true,
  },
  {
    id: 'invest_equipment',
    name: '設備投資',
    category: 'invest',
    categoryLabel: '投資',
    icon: '🖥️',
    description: '良い機材を揃える。品質UPで単価が上がる。',
    cost: 800000,
    permanent: true,
    permanentEffect: { revenueMultiplier: 1.10 },
    permanentLabel: '売上+10%',
    failRate: 0,
    rarity: 2,
    count: 1,
    period: 2,
    unique: true,
  },

  // === 人材系 ===
  {
    id: 'hr_parttime',
    name: 'バイトを雇う',
    category: 'hr',
    categoryLabel: '人材',
    icon: '👤',
    description: 'まずはバイトから。売上の天井が上がる。',
    cost: 50000,
    permanent: true,
    permanentEffect: { revenueCap: 300000, monthlyExpense: 120000 },
    permanentLabel: '売上上限+Ƴ30万/月 / 人件費Ƴ12万/月',
    failRate: 0.10,
    failText: '面接したけど辞退された。採用費だけ消えた…。',
    successText: 'バイトのスズキさんが入社した！',
    rarity: 1,
    count: 2,
    period: 1,
    addsEmployee: {
      name: 'スズキ',
      type: 'parttime',
      baseSalary: 120000,
      ability: 'B',
      satisfaction: 60,
    },
  },
  {
    id: 'hr_fulltime',
    name: '正社員を雇う',
    category: 'hr',
    categoryLabel: '人材',
    icon: '👔',
    description: '正社員。能力は高いが固定費が重い。',
    cost: 100000,
    permanent: true,
    permanentEffect: { revenueCap: 600000, monthlyExpense: 280000 },
    permanentLabel: '売上上限+Ƴ60万/月 / 人件費Ƴ28万/月',
    failRate: 0.05,
    failText: '内定を出したが辞退された。',
    successText: '正社員のヤマダさんが入社した！',
    rarity: 2,
    count: 1,
    period: 2,
    addsEmployee: {
      name: 'ヤマダ',
      type: 'fulltime',
      baseSalary: 220000,
      ability: 'A',
      satisfaction: 70,
    },
  },
  {
    id: 'hr_outsource',
    name: '外注に依頼',
    category: 'hr',
    categoryLabel: '人材',
    icon: '📋',
    description: '今月だけ外注で増員。継続コストなし。',
    cost: 200000,
    revenueMin: 0,
    revenueMax: 0,
    revenueCap: 500000,
    failRate: 0.15,
    failText: '外注先の品質が微妙だった…。手直しに時間を取られた。',
    successText: '外注で今月のキャパが増えた！',
    rarity: 1,
    count: 2,
    period: 1,
    tempEffect: { revenueCap: 500000 },
  },

  // === 節税系 ===
  {
    id: 'tax_smallbiz',
    name: '小商人積立',
    category: 'tax',
    categoryLabel: '節税',
    icon: '🏦',
    description: '月Ƴ7万の積立で年間Ƴ84万を利益から控除。将来戻ってくる。',
    cost: 0,
    permanent: true,
    permanentEffect: { monthlyExpense: 70000, taxDeduction: 840000 },
    permanentLabel: '月Ƴ7万積立 / 年Ƴ84万の利益控除',
    failRate: 0,
    rarity: 2,
    count: 1,
    period: 2,
    unique: true,
  },
  {
    id: 'tax_safety',
    name: '安全共済機構',
    category: 'tax',
    categoryLabel: '節税',
    icon: '🛡️',
    description: '月Ƴ20万で年間Ƴ240万を経費化。取引先倒産時のセーフティネット。',
    cost: 0,
    permanent: true,
    permanentEffect: { monthlyExpense: 200000, taxDeduction: 2400000 },
    permanentLabel: '月Ƴ20万積立 / 年Ƴ240万を経費化',
    failRate: 0,
    rarity: 2,
    count: 1,
    period: 2,
    unique: true,
  },
  {
    id: 'tax_bonus',
    name: '決算賞与',
    category: 'tax',
    categoryLabel: '節税',
    icon: '🎁',
    description: '従業員にボーナスを出して経費にする。決算月のみ使用可。',
    cost: 0,
    failRate: 0,
    rarity: 2,
    count: 1,
    period: 2,
    requirement: { hasEmployees: true },
    requirementText: '従業員1人以上で解放',
    settlementOnly: true,
    interactive: true,
  },

  // === 特殊系 ===
  {
    id: 'special_loan',
    name: '融資申請',
    category: 'special',
    categoryLabel: '特殊',
    icon: '🏛️',
    description: '銀行から借りる。審査あり。',
    cost: 0,
    failRate: 0.40,
    failText: '審査の結果、今回は見送りとなりました。',
    successText: '融資が通った！',
    rarity: 3,
    count: 1,
    period: 2,
    interactive: true,
  },
  {
    id: 'special_subsidy',
    name: '助成金申請',
    category: 'special',
    categoryLabel: '特殊',
    icon: '📝',
    description: '国の助成金に応募。通れば返済不要のお金が入る。',
    cost: 0,
    revenueMin: 500000,
    revenueMax: 1000000,
    failRate: 0.50,
    failText: '不採択。書類が足りなかった…。',
    successText: '助成金に採択された！返済不要！',
    rarity: 3,
    count: 1,
    period: 2,
  },

  // === 休息 ===
  {
    id: 'rest',
    name: '休む',
    category: 'rest',
    categoryLabel: '休息',
    icon: '🏖️',
    description: '何もしない。でも体力は戻る。',
    cost: 0,
    failRate: 0,
    rarity: 1,
    count: 2,
    period: 1,
    restoreStamina: 20,
  },
];

// 山札を生成する（期に応じてフィルタ）
export function buildDeck(period, gameState) {
  const deck = [];
  for (const tmpl of CARD_TEMPLATES) {
    if (tmpl.period > period) continue;
    if (tmpl.unique && gameState.usedUniqueCards.includes(tmpl.id)) continue;
    if (tmpl.requirement) {
      if (tmpl.requirement.creditScore && gameState.creditScore < tmpl.requirement.creditScore) continue;
      if (tmpl.requirement.totalRevenue && gameState.totalRevenue < tmpl.requirement.totalRevenue) continue;
      if (tmpl.requirement.hasEmployees && gameState.employees.length === 0) continue;
    }
    for (let i = 0; i < tmpl.count; i++) {
      deck.push({ ...tmpl, instanceId: `${tmpl.id}_${i}_${Math.random().toString(36).slice(2, 8)}` });
    }
  }
  return shuffle(deck);
}

// 手札を引く
export function drawHand(deck, count = 5) {
  const hand = [];
  for (let i = 0; i < count && deck.length > 0; i++) {
    hand.push(deck.pop());
  }
  return hand;
}

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}